### ISSUE TITLE
The last step for the chat url 

### ISSUE THREAD

**Issue by glamperi** [redhat-ai-services/podman-ai-lab-to-rhoai#3]
In the elastic-vectordb-workbench-0 pod, I get a 404 error which prevents the final integration step from working.

[I 2024-10-01 21:45:34.266 ServerApp] nbclassic | extension was successfully loaded.
[I 2024-10-01 21:45:34.375 ServerApp] nbdime | extension was successfully loaded.
[I 2024-10-01 21:45:34.377 ServerApp] nbgitpuller | extension was successfully loaded.
[I 2024-10-01 21:45:34.378 ServerApp] Serving notebooks from local directory: /opt/app-root/src
[I 2024-10-01 21:45:34.378 ServerApp] Jupyter Server 2.13.0 is running at:
[I 2024-10-01 21:45:34.378 ServerApp] http://elastic-vectordb-workbench-0:8888/notebook/podman-ai-lab-rag-project/elastic-vectordb-workbench/lab
[I 2024-10-01 21:45:34.378 ServerApp] http://127.0.0.1:8888/notebook/podman-ai-lab-rag-project/elastic-vectordb-workbench/lab
[I 2024-10-01 21:45:34.378 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2024-10-01 21:45:35.172 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2024-10-01 21:45:44.594 ServerApp] 404 GET /notebook/podman-ai-lab-rag-project/elastic-vectordb-workbench/api/kernels/181fff32-3d86-4f06-8562-724a02fd478a?1727819144351 (127.0.0.1): Kernel does not exist: 181fff32-3d86-4f06-8562-724a02fd478a
[W 2024-10-01 21:45:44.595 ServerApp] wrote error: 'Kernel does not exist: 181fff32-3d86-4f06-8562-724a02fd478a'
Traceback (most recent call last):
File "/opt/app-root/lib64/python3.9/site-packages/tornado/web.py", line 1790, in _execute
result = await result
File "/opt/app-root/lib64/python3.9/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
return await out
File "/opt/app-root/lib64/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 74, in get
model = await ensure_async(km.kernel_model(kernel_id))

**Comment by jhurlocker** [comment]
It looks like something might be wrong when you're starting up your workbench. This is the log file from my workbench. Instead of getting a 404 I'm getting a 302. What version of OpenShift and OpenShift AI are you using?

```
[I 2024-10-02 03:05:48.133 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2024-10-02 03:06:19.494 ServerApp] 302 GET /notebook/podman-ai-lab-rag-project/elastic-vectordb-workbench (@127.0.0.1) 0.74ms
[I 2024-10-02 03:06:42.846 LabApp] Build is up to date
[I 2024-10-02 03:07:13.267 ServerApp] Uploading file to /Langchain-ElasticSearchVector-Ingest.ipynb
```

**Comment by glamperi** [comment]
It looks like it is 2.13.0.  I do see a failure now that you have me looking at the operator, although not sure what failed.
<img width="1117" alt="Screenshot 2024-10-02 at 10 31 10 AM" src="https://github.com/user-attachments/assets/dead6b50-7262-40df-ad8f-6c91f90a3773">

**Comment by jhurlocker** [comment]
You might not have enough resources to install all of the components on your cluster. Did you install other operators and deploy other applications on the cluster?
